import React,{useMemo,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {ArrowRight,ChevronDown,Heart,Menu,X,Search,ShieldCheck,Sparkles,MapPin,Phone,CheckCircle2,SlidersHorizontal,RotateCcw,CalendarDays,Gauge,Fuel,KeyRound,Star,ChevronLeft,ChevronRight} from 'lucide-react';
import './styles.css';

const IMG={
 hero:'https://images.unsplash.com/photo-1503376780353-7e6692767b70?auto=format&fit=crop&w=2200&q=88',
 bmw:'https://images.unsplash.com/photo-1555215695-3004980ad54e?auto=format&fit=crop&w=1400&q=88',
 suv:'https://images.unsplash.com/photo-1606664515524-ed2f786a0bd6?auto=format&fit=crop&w=1400&q=88',
 mercedes:'https://images.unsplash.com/photo-1618843479313-40f8afb4b4d8?auto=format&fit=crop&w=1400&q=88',
 ferrari:'https://images.unsplash.com/photo-1592198084033-aade902d1aae?auto=format&fit=crop&w=1400&q=88',
 lambo:'https://images.unsplash.com/photo-1544829099-b9a0c07fad1a?auto=format&fit=crop&w=1400&q=88',
 bentley:'https://images.unsplash.com/photo-1563720223185-11003d516935?auto=format&fit=crop&w=1400&q=88',
 porsche:'https://images.unsplash.com/photo-1503376780353-7e6692767b70?auto=format&fit=crop&w=1400&q=88',
 luxury:'https://images.unsplash.com/photo-1542282088-fe8426682b8f?auto=format&fit=crop&w=1400&q=88',
 sedan:'https://images.unsplash.com/photo-1553440569-bcc63803a83d?auto=format&fit=crop&w=1400&q=88'
};

const cars=[
{id:1,brand:'BMW',model:'5 Series 530i M Sport',year:2022,price:4850000,km:32000,fuel:'Petrol',gear:'Automatic',city:'Pune',type:'Sedan',badge:'Featured',img:IMG.bmw,engine:'2.0L Turbo',owners:1,color:'Carbon Black',desc:'Executive luxury with sharp M Sport styling, premium leather cabin and a confident turbocharged drive.'},
{id:2,brand:'BMW',model:'X5 xDrive40i M Sport',year:2023,price:9250000,km:18500,fuel:'Petrol',gear:'Automatic',city:'Mumbai',type:'SUV',badge:'Certified',img:IMG.suv,engine:'3.0L Turbo',owners:1,color:'Black Sapphire',desc:'A commanding luxury SUV combining effortless performance, comfort and everyday practicality.'},
{id:3,brand:'BMW',model:'X7 xDrive40i',year:2023,price:11800000,km:12000,fuel:'Petrol',gear:'Automatic',city:'Delhi',type:'SUV',badge:'New Arrival',img:IMG.luxury,engine:'3.0L Turbo',owners:1,color:'Mineral White',desc:'Three-row flagship SUV with executive seating, panoramic ambience and long-distance comfort.'},
{id:4,brand:'Mercedes-Benz',model:'E 350d AMG Line',year:2022,price:6150000,km:27000,fuel:'Diesel',gear:'Automatic',city:'Pune',type:'Sedan',badge:'Certified',img:IMG.mercedes,engine:'3.0L Diesel',owners:1,color:'Obsidian Black',desc:'Refined E-Class comfort with AMG detailing, strong diesel torque and a beautifully finished cabin.'},
{id:5,brand:'Mercedes-Benz',model:'GLE 300d 4MATIC',year:2023,price:7900000,km:21000,fuel:'Diesel',gear:'Automatic',city:'Mumbai',type:'SUV',badge:'Popular',img:IMG.suv,engine:'2.0L Diesel',owners:1,color:'Graphite Grey',desc:'Premium SUV with plush ride quality, intelligent all-wheel drive and a high-tech interior.'},
{id:6,brand:'Mercedes-Benz',model:'G 63 AMG',year:2024,price:34500000,km:3500,fuel:'Petrol',gear:'Automatic',city:'Mumbai',type:'Performance SUV',badge:'Ultra Rare',img:IMG.mercedes,engine:'4.0L V8',owners:1,color:'Manufaktur Black',desc:'Iconic G-Class presence with hand-finished luxury and AMG performance.'},
{id:7,brand:'Audi',model:'A6 Technology',year:2022,price:5650000,km:24000,fuel:'Petrol',gear:'Automatic',city:'Pune',type:'Sedan',badge:'Certified',img:IMG.sedan,engine:'2.0L TFSI',owners:1,color:'Mythos Black',desc:'Elegant business-class sedan with quattro-inspired confidence and a technology-rich cabin.'},
{id:8,brand:'Audi',model:'Q8 55 TFSI',year:2023,price:8900000,km:17000,fuel:'Petrol',gear:'Automatic',city:'Delhi',type:'SUV Coupe',badge:'Featured',img:IMG.luxury,engine:'3.0L TFSI',owners:1,color:'Glacier White',desc:'Sleek flagship SUV coupe with a sophisticated interior and effortless highway performance.'},
{id:9,brand:'Land Rover',model:'Range Rover Sport HSE',year:2022,price:13200000,km:29500,fuel:'Diesel',gear:'Automatic',city:'Mumbai',type:'Luxury SUV',badge:'Featured',img:IMG.suv,engine:'3.0L Diesel',owners:1,color:'Santorini Black',desc:'A modern Range Rover Sport with commanding road presence, luxury comfort and genuine capability.'},
{id:10,brand:'Land Rover',model:'Range Rover Velar R-Dynamic',year:2023,price:7600000,km:16000,fuel:'Petrol',gear:'Automatic',city:'Pune',type:'Luxury SUV',badge:'Certified',img:IMG.suv,engine:'2.0L Turbo',owners:1,color:'Fuji White',desc:'Minimalist luxury SUV with dramatic design, refined road manners and a premium cabin.'},
{id:11,brand:'Porsche',model:'911 Carrera',year:2023,price:27500000,km:7200,fuel:'Petrol',gear:'PDK',city:'Delhi',type:'Sports Car',badge:'Collector Pick',img:IMG.porsche,engine:'3.0L Flat-6',owners:1,color:'Guards Red',desc:'An iconic driver-focused sports car balancing daily usability with legendary Porsche character.'},
{id:12,brand:'Porsche',model:'Cayenne S',year:2022,price:11800000,km:19800,fuel:'Petrol',gear:'Automatic',city:'Mumbai',type:'Performance SUV',badge:'Popular',img:IMG.porsche,engine:'2.9L V6',owners:1,color:'Jet Black',desc:'Performance SUV with sports-car DNA, premium comfort and strong long-distance capability.'},
{id:13,brand:'Lexus',model:'LX 500d',year:2023,price:13200000,km:14000,fuel:'Diesel',gear:'Automatic',city:'Mumbai',type:'Luxury SUV',badge:'Premium',img:IMG.luxury,engine:'3.3L Diesel',owners:1,color:'Sonic Quartz',desc:'Ultra-comfortable flagship SUV known for craftsmanship, durability and serene road presence.'},
{id:14,brand:'Jaguar',model:'F-PACE R-Dynamic S',year:2022,price:5850000,km:26000,fuel:'Petrol',gear:'Automatic',city:'Pune',type:'SUV',badge:'Certified',img:IMG.luxury,engine:'2.0L Turbo',owners:1,color:'Santorini Black',desc:'Distinctive British luxury with sporty handling, rich materials and confident proportions.'},
{id:15,brand:'Maserati',model:'Levante GT',year:2022,price:10200000,km:11000,fuel:'Petrol',gear:'Automatic',city:'Mumbai',type:'Luxury SUV',badge:'Rare',img:IMG.luxury,engine:'2.0L Hybrid',owners:1,color:'Nero',desc:'Italian grand-touring attitude in SUV form, with a beautifully tailored cabin and strong road character.'},
{id:16,brand:'Bentley',model:'Continental GT',year:2022,price:41000000,km:5400,fuel:'Petrol',gear:'Automatic',city:'Mumbai',type:'Luxury Coupe',badge:'Ultra Rare',img:IMG.bentley,engine:'4.0L V8',owners:1,color:'Onyx Black',desc:'Handcrafted grand tourer blending extraordinary materials, effortless power and timeless design.'},
{id:17,brand:'Ferrari',model:'Roma',year:2022,price:48500000,km:6100,fuel:'Petrol',gear:'DCT',city:'Mumbai',type:'Grand Tourer',badge:'Collector Pick',img:IMG.ferrari,engine:'3.9L V8',owners:1,color:'Rosso Corsa',desc:'Elegant modern Ferrari grand tourer with dramatic styling and exhilarating performance.'},
{id:18,brand:'Lamborghini',model:'Huracán EVO',year:2021,price:39000000,km:9800,fuel:'Petrol',gear:'DCT',city:'Pune',type:'Supercar',badge:'Iconic',img:IMG.lambo,engine:'5.2L V10',owners:1,color:'Nero Noctis',desc:'Naturally aspirated V10 drama, sharp design and unmistakable Lamborghini theatre.'},
{id:19,brand:'Rolls-Royce',model:'Ghost',year:2023,price:72500000,km:8200,fuel:'Petrol',gear:'Automatic',city:'Mumbai',type:'Ultra Luxury Sedan',badge:'By Appointment',img:IMG.luxury,engine:'6.75L V12',owners:1,color:'Black Diamond',desc:'The definitive expression of quiet luxury, handcrafted detail and effortless V12 performance.'},
{id:20,brand:'Volvo',model:'XC90 Recharge',year:2023,price:9250000,km:12500,fuel:'Hybrid',gear:'Automatic',city:'Delhi',type:'Luxury SUV',badge:'Eco Luxury',img:IMG.suv,engine:'2.0L Hybrid',owners:1,color:'Crystal White',desc:'Scandinavian luxury with three-row practicality, advanced safety and plug-in hybrid efficiency.'}
];
const brands=['All','BMW','Mercedes-Benz','Audi','Land Rover','Porsche','Lexus','Jaguar','Maserati','Bentley','Ferrari','Lamborghini','Rolls-Royce','Volvo'];
const money=n=>n>=10000000?`₹${(n/10000000).toFixed(n%10000000?1:0)} Cr`:`₹${(n/100000).toFixed(1)} L`;
const full=n=>`₹${n.toLocaleString('en-IN')}`;

function App(){
 const [menu,setMenu]=useState(false),[brand,setBrand]=useState('All'),[query,setQuery]=useState(''),[city,setCity]=useState('All Cities'),[fuel,setFuel]=useState('All'),[type,setType]=useState('All'),[liked,setLiked]=useState([]),[selected,setSelected]=useState(null),[showFilters,setShowFilters]=useState(false),[sort,setSort]=useState('featured');
 const filtered=useMemo(()=>{let a=cars.filter(c=>(brand==='All'||c.brand===brand)&&(city==='All Cities'||c.city===city)&&(fuel==='All'||c.fuel===fuel)&&(type==='All'||c.type===type)&&`${c.brand} ${c.model} ${c.type}`.toLowerCase().includes(query.toLowerCase()));if(sort==='low')a.sort((x,y)=>x.price-y.price);if(sort==='high')a.sort((x,y)=>y.price-x.price);if(sort==='new')a.sort((x,y)=>y.year-x.year);return a},[brand,query,city,fuel,type,sort]);
 const toggle=id=>setLiked(v=>v.includes(id)?v.filter(x=>x!==id):[...v,id]);
 const reset=()=>{setBrand('All');setQuery('');setCity('All Cities');setFuel('All');setType('All');setSort('featured')};
 return <div className="app">
  <div className="announcement"><span>CURATED PRE-OWNED LUXURY</span><span className="annRight">Inspected · Verified · Concierge Delivery</span></div>
  <header className="nav"><a className="logo" href="#home"><span className="logoMark">A</span><span>AUTOVAULT <i>AUTOMOTIVE</i></span></a><nav className={menu?'links open':'links'}><a href="#inventory" onClick={()=>setMenu(false)}>Inventory</a><a href="#brands" onClick={()=>setMenu(false)}>Marques</a><a href="#standard" onClick={()=>setMenu(false)}>The Standard</a><a href="#contact" onClick={()=>setMenu(false)}>Contact</a></nav><div className="navActions"><a className="navPhone" href="tel:+919876543210"><Phone size={15}/> +91 98765 43210</a><a className="navButton" href="#inventory">Explore Cars <ArrowRight size={15}/></a><button className="menu" onClick={()=>setMenu(!menu)}>{menu?<X/>:<Menu/>}</button></div></header>
  <main>
   <section className="hero" id="home"><div className="heroImage"><img src={IMG.hero}/><div className="heroGradient"/><div className="heroTag"><Sparkles size={14}/> PRIVATE COLLECTION</div><div className="heroCaption"><span>THE AUTOVAULT EDIT</span><strong>Performance, <em>perfected.</em></strong><p>Handpicked luxury cars for clients who expect more from every mile.</p></div></div><div className="heroCopy"><div className="eyebrow"><span/> CURATED AUTOMOTIVE EXCELLENCE</div><h1>Drive the<br/><em>exceptional.</em></h1><p>Discover a refined collection of premium pre-owned automobiles, professionally inspected and prepared for a first-class ownership experience.</p><div className="heroBtns"><a className="goldBtn" href="#inventory">Explore collection <ArrowRight size={17}/></a><a className="textBtn" href="#contact">Speak to a specialist</a></div><div className="proof"><div><b>200+</b><span>Inspection points</span></div><div><b>4.9/5</b><span>Client rating</span></div><div><b>48 hrs</b><span>Delivery support</span></div></div></div></section>
   <section className="marques" id="brands"><div className="sectionKicker">THE MARQUES</div><div className="marqueIntro"><h2>The names<br/><em>worth knowing.</em></h2><p>A considered selection of the world's most desirable luxury, performance and executive marques.</p></div><div className="brandRow">{brands.slice(1,9).map(b=><button key={b} onClick={()=>{setBrand(b);document.getElementById('inventory').scrollIntoView({behavior:'smooth'})}}>{b}<ArrowRight size={14}/></button>)}</div></section>
   <section className="inventory" id="inventory"><div className="inventoryHead"><div><div className="sectionKicker">THE COLLECTION · {filtered.length} CARS</div><h2>Find your <em>next icon.</em></h2></div><div className="search"><Search size={18}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search BMW, Range Rover, 911…"/></div></div>
    <div className="filterBar"><button className="filterToggle" onClick={()=>setShowFilters(!showFilters)}><SlidersHorizontal size={16}/> Filters</button><div className="chips">{['All','BMW','Mercedes-Benz','Land Rover','Porsche'].map(b=><button key={b} className={brand===b?'active':''} onClick={()=>setBrand(b)}>{b}</button>)}</div><div className="sort"><span>Sort by</span><select value={sort} onChange={e=>setSort(e.target.value)}><option value="featured">Featured</option><option value="new">Newest</option><option value="low">Price: Low</option><option value="high">Price: High</option></select></div></div>
    {showFilters&&<div className="advanced"><label>City<select value={city} onChange={e=>setCity(e.target.value)}><option>All Cities</option><option>Mumbai</option><option>Pune</option><option>Delhi</option></select></label><label>Body type<select value={type} onChange={e=>setType(e.target.value)}><option>All</option><option>SUV</option><option>Sedan</option><option>Sports Car</option><option>Luxury SUV</option><option>Luxury Coupe</option><option>Supercar</option></select></label><label>Fuel<select value={fuel} onChange={e=>setFuel(e.target.value)}><option>All</option><option>Petrol</option><option>Diesel</option><option>Hybrid</option></select></label><button onClick={reset}><RotateCcw size={14}/> Reset all</button></div>}
    <div className="grid">{filtered.map(c=><article className="card" key={c.id}><div className="cardImg"><img src={c.img} alt={`${c.brand} ${c.model}`}/><span className="badge">{c.badge}</span><button className={liked.includes(c.id)?'like liked':'like'} onClick={()=>toggle(c.id)}><Heart size={18} fill={liked.includes(c.id)?'currentColor':'none'}/></button><div className="quick">View details <ArrowRight size={15}/></div></div><div className="cardBody"><div className="brandName">{c.brand}</div><h3>{c.model}</h3><div className="meta"><span><CalendarDays size={13}/>{c.year}</span><span><Gauge size={13}/>{c.km.toLocaleString('en-IN')} km</span><span><Fuel size={13}/>{c.fuel}</span></div><div className="priceLine"><div><small>ASKING PRICE</small><strong>{money(c.price)}</strong></div><button onClick={()=>setSelected(c)}>Details <ArrowRight size={15}/></button></div></div></article>)}</div>
    {!filtered.length&&<div className="empty"><Search size={28}/><h3>No matching cars</h3><p>Try another marque or reset your filters.</p><button onClick={reset}>Reset search</button></div>}
   </section>
   <section className="manifesto"><div className="manifestoInner"><div className="sectionKicker">MORE THAN A CAR</div><h2>Luxury is not a feature.<br/><em>It is the experience.</em></h2><p>From the first conversation to the moment your car arrives, AutoVault is designed around discretion, confidence and impeccable attention to detail.</p></div></section>
   <section className="standard" id="standard"><div className="standardHead"><div><div className="sectionKicker">THE AUTOVAULT STANDARD</div><h2>Confidence,<br/><em>built in.</em></h2></div><p>Every vehicle is selected for provenance, condition, specification and character — then prepared to our own exacting standard.</p></div><div className="standGrid"><div><span>01</span><ShieldCheck/><h3>200+ Point Inspection</h3><p>Mechanical, electrical, structural, paint and interior checks before a car joins the collection.</p></div><div><span>02</span><CheckCircle2/><h3>Verified Provenance</h3><p>Ownership, documentation and condition details are presented clearly, without surprises.</p></div><div><span>03</span><KeyRound/><h3>Concierge Delivery</h3><p>Finance, insurance and doorstep delivery support from one dedicated automotive specialist.</p></div><div><span>04</span><Star/><h3>Curated Inventory</h3><p>We would rather show twenty exceptional cars than two hundred ordinary ones.</p></div></div></section>
   <section className="cta" id="contact"><div className="ctaBg"><img src={IMG.hero}/></div><div className="ctaContent"><div className="sectionKicker">CAN'T FIND THE ONE?</div><h2>Let us source<br/><em>your next car.</em></h2><p>Tell us the marque, model or specification you have in mind. Our sourcing team can access rare and hard-to-find vehicles across our network.</p><div className="ctaBtns"><a className="goldBtn" href="mailto:hello@autovault.in">Request a car <ArrowRight size={17}/></a><a className="outlineBtn" href="tel:+919876543210"><Phone size={15}/> Call a specialist</a></div></div></section>
  </main>
  <footer><div className="footerTop"><div><a className="logo"><span className="logoMark">A</span><span>AUTOVAULT <i>AUTOMOTIVE</i></span></a><p>Curated luxury. Verified quality.<br/>A better way to buy pre-owned.</p></div><div><h4>Explore</h4><a href="#inventory">Inventory</a><a href="#brands">Marques</a><a href="#standard">The Standard</a></div><div><h4>Services</h4><a href="#contact">Car sourcing</a><a href="#contact">Sell your car</a><a href="#contact">Finance</a></div><div><h4>Concierge</h4><p><MapPin size={14}/> Mumbai · Pune · Delhi</p><p><Phone size={14}/> +91 98765 43210</p><p>hello@autovault.in</p></div></div><div className="footerBottom"><span>© 2026 AutoVault · Frontend concept</span><span>Privacy · Terms · Dealer disclosure</span></div></footer>
  {selected&&<div className="modal" onMouseDown={e=>e.target===e.currentTarget&&setSelected(null)}><div className="modalCard"><button className="close" onClick={()=>setSelected(null)}><X/></button><div className="modalImg"><img src={selected.img} alt=""/></div><div className="modalInfo"><div className="sectionKicker">{selected.badge}</div><div className="brandName">{selected.brand}</div><h2>{selected.model}</h2><strong className="modalPrice">{full(selected.price)}</strong><p>{selected.desc}</p><div className="specs"><div><small>YEAR</small><b>{selected.year}</b></div><div><small>RUN</small><b>{selected.km.toLocaleString('en-IN')} km</b></div><div><small>ENGINE</small><b>{selected.engine}</b></div><div><small>GEARBOX</small><b>{selected.gear}</b></div><div><small>OWNERS</small><b>{selected.owners}</b></div><div><small>COLOUR</small><b>{selected.color}</b></div></div><a className="goldBtn full" href="tel:+919876543210">Enquire about this car <ArrowRight size={17}/></a></div></div></div>}
 </div>
}
createRoot(document.getElementById('root')).render(<App/>);
